"""Add Product model for tick-aware reconciliation

Revision ID: 002
Revises: 001
Create Date: 2024-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('tick_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contract_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_products_exchange'), 'products', ['exchange'], unique=False)
    op.create_index(op.f('ix_products_symbol'), 'products', ['symbol'], unique=False)
    op.create_index('ix_products_symbol_exchange', 'products', ['symbol', 'exchange'], unique=False)
    op.create_index('ix_products_type_active', 'products', ['product_type', 'is_active'], unique=False)
    
    # Insert default product configurations for common ETD instruments
    op.execute("""
        INSERT INTO products (id, symbol, product_type, exchange, name, tick_size, tick_value, contract_size, is_active, currency, asset_class, created_at, updated_at)
        VALUES 
        (gen_random_uuid(), 'ES', 'ETD', 'CME', 'E-mini S&P 500 Futures', 0.25, 12.50, 50, true, 'USD', 'Equity Index', now(), now()),
        (gen_random_uuid(), 'NQ', 'ETD', 'CME', 'E-mini NASDAQ-100 Futures', 0.25, 5.00, 20, true, 'USD', 'Equity Index', now(), now()),
        (gen_random_uuid(), 'CL', 'ETD', 'NYMEX', 'Crude Oil Futures', 0.01, 10.00, 1000, true, 'USD', 'Energy', now(), now()),
        (gen_random_uuid(), 'GC', 'ETD', 'COMEX', 'Gold Futures', 0.10, 10.00, 100, true, 'USD', 'Precious Metals', now(), now())
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_type_active', table_name='products')
    op.drop_index('ix_products_symbol_exchange', table_name='products')
    op.drop_index(op.f('ix_products_symbol'), table_name='products')
    op.drop_index(op.f('ix_products_exchange'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
