version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=opspilot
      - POSTGRES_PASSWORD=opspilot
      - POSTGRES_DB=opspilot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    environment:
      - CORS_ALLOW_ORIGINS=http://localhost:3000,http://localhost:5173
      - AI_ENABLED=false
      - OPENAI_API_KEY=
      - DATABASE_URL=postgresql+psycopg2://opspilot:opspilot@db:5432/opspilot
      - REDIS_URL=redis://redis:6379/0
      - USE_CELERY=false
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./sample_data:/app/sample_data
      - backend_tmp:/tmp
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  web:
    build:
      context: ./apps/web
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: sh -lc "npm install && npm run dev -- --host"
    depends_on:
      - backend

  worker:
    build:
      context: ./backend
    command: bash -lc "celery -A app.tasks.celery_app worker --loglevel=INFO"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

volumes:
  backend_tmp:
  db_data:


