name: Frontend CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install frontend dependencies
        working-directory: apps/web
        run: bun install
      - name: Run linting
        working-directory: apps/web
        run: bun run lint || true
      - name: Build frontend
        working-directory: apps/web
        run: bun run build
